import Link from "next/link";
import { notFound } from "next/navigation";
import { costChange, dateBR, dateTimeBR, money, snapshot, statusClass, works } from "../../../data";
import { SiteShell } from "../../../site-shell";

export default async function WorkPage({params}:{params:Promise<{id:string;slug:string}>}) {
  const {id} = await params;
  const work = works.find((item) => String(item.id) === id);
  if (!work) notFound();
  const change = costChange(work);
  const deadlinePassed = work.status !== "Concluída" && Boolean(work.contract.executionLimit && work.contract.executionLimit < snapshot.collectedAt.slice(0,10));
  return <SiteShell>
    <div className="work-head civic-work-head"><div><Link href="/obras">← Voltar à lista</Link><p className="eyebrow">Registro EngeGOV #{work.code}</p><h1>{work.name}</h1><p>{work.intervention} · {work.address} · {work.secretariat}</p><span className={`status ${statusClass(work.status)}`}>{work.status}</span></div><div className="source-stamp"><span className="live-dot">Fonte pública</span><b>EngeGOV Blumenau</b><span>Coletado em {dateTimeBR(work.collectedAt)}</span><a href={work.sourceUrl} target="_blank" rel="noreferrer">Conferir registro oficial ↗</a></div></div>
    <nav className="tabs" aria-label="Seções da obra"><a href="#resumo">Resumo</a><a href="#prazo">Prazo</a><a href="#custos">Custos</a><a href="#medicoes">Medições</a><a href="#contrato">Contrato</a><a href="#fonte">Fonte</a></nav>
    <section id="resumo" className="detail-grid"><article><h2>O essencial para fiscalizar</h2><dl className="facts"><div><dt>Situação publicada</dt><dd>{work.status}</dd></div><div><dt>Local informado</dt><dd>{work.address}</dd></div><div><dt>Responsável municipal</dt><dd>{work.secretariat}</dd></div><div><dt>Empresa</dt><dd>{work.contract.company ?? "Não informada"}</dd></div><div><dt>Ciclo do contrato</dt><dd>{work.mandate}</dd></div></dl></article><aside className="dual-status"><h2>Leitura cidadã</h2><div><small>Avanço físico publicado/calculável</small><b>{work.physicalProgress == null ? "Não informado" : `${work.physicalProgress.toLocaleString("pt-BR")}%`}</b></div><div><small>Variação entre valores</small><b>{change == null ? "Não calculável" : `${change > 0 ? "+" : ""}${change.toFixed(1)}%`}</b></div><p>Esses números ajudam a selecionar o que verificar. Não provam atraso injustificado ou irregularidade.</p></aside></section>
    <section className="detail-section" id="prazo"><h2>Linha do tempo contratual</h2><div className="deadline-grid"><div><small>Contrato</small><b>{dateBR(work.contract.date)}</b></div><div><small>Início da obra</small><b>{dateBR(work.contract.startDate)}</b></div><div className={deadlinePassed?"deadline-alert":""}><small>Data limite de execução</small><b>{dateBR(work.contract.executionLimit)}</b>{deadlinePassed&&<em>Anterior à data de corte</em>}</div><div><small>Término do contrato</small><b>{dateBR(work.contract.contractEnd)}</b></div><div><small>Data de conclusão</small><b>Não publicada nesta ficha</b></div></div><p className="method-note"><b>Como cobrar:</b> se a data limite passou e a obra continua ativa, peça o aditivo, a ordem de suspensão/reinício e o cronograma atualizado. A data de término do contrato não é necessariamente a data física de conclusão.</p></section>
    <section className="detail-section" id="custos"><h2>Valores publicados</h2><div className="cost-cards"><div><small>Valor inicial contratado</small><b>{money(work.initialValue)}</b></div><div><small>Valor atual</small><b>{money(work.currentValue)}</b><small>{change == null ? "sem base de comparação" : `${change > 0 ? "+" : ""}${change.toFixed(1)}% sobre o inicial`}</small></div><div><small>Valor medido</small><b>{money(work.executedValue)}</b></div><div><small>Saldo publicado</small><b>{money(work.execution.balance)}</b></div></div>{change != null && change > 20 && <p className="alert-note"><b>Ponto de atenção:</b> o aumento supera 20%. Verifique se decorre de reajuste, reequilíbrio, acréscimo de escopo ou outro instrumento formal.</p>}<p className="method-note">Valor medido não é necessariamente valor pago. O portal mostra a execução contratual; para despesa orçamentária, confronte também empenhos, liquidações e pagamentos.</p></section>
    <section className="detail-section" id="medicoes"><h2>Medições ({work.measurements.length})</h2>{work.measurements.length ? <div className="measurement-list">{work.measurements.map((measurement) => <article key={`${measurement.number}-${measurement.date}`}><span>Medição {measurement.number}</span><b>{dateBR(measurement.date)}</b><dl><div><dt>Percentual medido</dt><dd>{measurement.percentMeasured?.toLocaleString("pt-BR") ?? "—"}%</dd></div><div><dt>Valor medido</dt><dd>{money(measurement.measuredValue)}</dd></div><div><dt>Acumulado</dt><dd>{measurement.accumulatedPercent?.toLocaleString("pt-BR") ?? "—"}% · {money(measurement.accumulatedValue)}</dd></div></dl></article>)}</div> : <p className="empty-state">Nenhuma medição foi localizada na ficha pública desta obra.</p>}</section>
    <section className="detail-section" id="contrato"><h2>Identificação do contrato</h2><dl className="facts contract-facts"><div><dt>Número</dt><dd>{work.contract.number ?? "Não informado"}</dd></div><div><dt>Licitação</dt><dd>{work.contract.procurementNumber ?? "Não informada"}</dd></div><div><dt>Ordem de serviço</dt><dd>{work.contract.serviceOrder ?? "Não informada"}</dd></div><div><dt>Empresa</dt><dd>{work.contract.company ?? "Não informada"}</dd></div><div><dt>CNPJ</dt><dd>{work.contract.cnpj ?? "Não informado"}</dd></div><div><dt>Recurso</dt><dd>{work.contract.resourceType ?? "Não informado"}</dd></div></dl></section>
    <section className="detail-section source-audit" id="fonte"><h2>Origem e rastreabilidade</h2><p><b>Fonte:</b> {snapshot.source}. <b>Coleta:</b> {dateTimeBR(work.collectedAt)}. <b>Hash do registro:</b> <code>{work.contentHash}</code>.</p><p>Limitação: o EngeGOV é a fonte primária desta fotografia. Documentos de aditivos, pagamentos e decisões de controle devem ser confrontados em suas fontes oficiais.</p><a className="button primary" href={work.sourceUrl} target="_blank" rel="noreferrer">Abrir EngeGOV</a></section>
  </SiteShell>;
}
