import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "../site-shell";

const pages:Record<string,{title:string;intro:string;items:string[]}>= {
  "metodologia":{title:"Entenda os dados",intro:"Como transformamos registros públicos em informação comparável, explicável e cautelosa.",items:["A fotografia contém 483 registros coletados do EngeGOV em 16/07/2026.","Concluídas é um estoque histórico; em andamento e paralisadas são a situação atual. Esses universos não são usados um contra o outro.","Os ciclos de quatro anos agrupam pela data do contrato. A situação exibida continua sendo a situação atual.","Uma obra que atravessa governos não é atribuída integralmente a um único prefeito.","Aumento de custo compara valor inicial e atual somente quando ambos estão publicados.","Alertas são pedidos de verificação e não acusações ou conclusões legais."]},
  "prazos-e-custos":{title:"Prazos e custos",intro:"Compare datas e valores do mesmo contrato, sem misturar execução física, vigência e pagamento.",items:["A ficha separa assinatura, início, data limite de execução e término do contrato.","Uma data original vencida gera triagem; aditivos e suspensões podem alterar a análise.","O aumento percentual é (valor atual − valor inicial) ÷ valor inicial × 100.","Reajuste, reequilíbrio, mudança de escopo, acréscimo e supressão exigem documentos próprios.","Valor medido não é necessariamente valor pago.","Ausência de informação na ficha não prova inexistência do documento."]},
  "transparencia":{title:"Transparência documental",intro:"O caminho entre um alerta e uma cobrança responsável passa pelos documentos.",items:["Anote código, contrato, secretaria, empresa, data e valor.","Peça o aditivo ou ato que alterou prazo, valor ou escopo.","Confronte medições com empenhos, liquidações e pagamentos no Portal da Transparência.","Guarde a resposta oficial e a data da consulta."]},
  "dados-abertos":{title:"Dados abertos",intro:"A fotografia pública é preservada com metadados e rastreabilidade.",items:["O repositório inclui o JSON coletado do EngeGOV.","Cada registro possui URL da fonte, data de coleta e hash de conteúdo.","A API oferece documentação OpenAPI em /docs quando o backend está ativo."]},
  "ajuda":{title:"Como fiscalizar",intro:"Transforme uma impressão em uma pergunta pública verificável.",items:["Localize a obra pelo código, rua, secretaria ou número do contrato.","Compare a situação atual com as datas e a última medição.","Se houver aumento, identifique o percentual e peça o instrumento que o autorizou.","Se o prazo passou, peça o cronograma atualizado, aditivos e atos de suspensão ou reinício.","Não atribua culpa ou ilegalidade sem documento e decisão do órgão competente."]},
  "glossario":{title:"Glossário cidadão",intro:"Termos técnicos em linguagem simples.",items:["Avanço físico: percentual de execução da obra ou serviço.","Medição: registro de quantidade ou etapa executada para fins contratuais.","Termo aditivo: instrumento que formaliza mudança no contrato.","Empenho: reserva orçamentária; não significa que o valor já foi pago."]},
  "atencao":{title:"Pontos de atenção",intro:"Filtros para priorizar leitura documental, sem acusações automáticas.",items:["Variação de custo acima de 20%.","Data limite original anterior à coleta em obra ainda ativa.","Paralisação publicada pela fonte.","Campos importantes não informados na ficha pública."]},
  "acessibilidade":{title:"Acessibilidade",intro:"O portal busca WCAG 2.2 AA e eMAG.",items:["Navegação por teclado e link para pular conteúdo.","Situações identificadas por texto e cor.","Tabelas com cabeçalhos e rolagem em telas pequenas.","Controles de contraste e tamanho do texto."]},
  "privacidade":{title:"Privacidade",intro:"A consulta pública não exige cadastro nem localização.",items:["Mensagens de contato coletam somente dados necessários para resposta.","Não envie dados pessoais desnecessários ou sigilosos.","A assistente local responde por regras controladas e não faz julgamento jurídico."]},
  "fontes":{title:"Fontes oficiais",intro:"A origem dos dados permanece visível em cada etapa.",items:["Portal EngeGOV de Blumenau: situação, identificação contratual, valores e medições.","Portal da Transparência, PNCP e Diário Oficial devem ser usados para confronto documental e financeiro.","Cada ficha deste projeto liga diretamente para o EngeGOV e preserva o hash do registro coletado."]},
};

export default async function Section({params}:{params:Promise<{section:string}>}) {
  const {section}=await params;
  const page=pages[section];
  if(!page)notFound();
  return <SiteShell><div className="page-head"><p className="eyebrow">Informação cidadã</p><h1>{page.title}</h1><p>{page.intro}</p></div><section className="content-card"><ol>{page.items.map((item,index)=><li key={item}><b>{String(index+1).padStart(2,"0")}</b><p>{item}</p></li>)}</ol><div className="callout"><b>Use a assistente</b><p>A IA do portal explica termos e ajuda a formular perguntas, mas não substitui órgãos de controle.</p><Link href="/">Voltar ao painel →</Link></div></section></SiteShell>;
}
